name: Waka Readme

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight every day
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Cache WakaTime Data
        id: wakatime
        run: |
          mkdir -p $HOME/.wakatime
          echo "[settings]" > $HOME/.wakatime.cfg
          echo "api_key = ${{ secrets.WAKATIME_API_KEY }}" >> $HOME/.wakatime.cfg
      - name: Update README
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        run: |
          npx wakatime-readme-stats
      - name: Commit Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'Updated WakaTime stats'
          git push
